version: 2.1

orbs:
  node: circleci/node@3.0.0
  cypress: cypress-io/cypress@1.26.0
  # heroku: circleci/heroku@1.0.1

jobs:
  build:
    docker:
      - image: cimg/node:13.11.0

    steps: 
      - checkout
      - run: npm install
  deploy:
    steps:
      - run:
          command: curl -X POST -d {} ${hook}

workflows:
  matrix-tests:
    jobs:
      - build
      - node/test:
          name: test1
          version: 13.11.0
          requires: 
            - build
      - node/test:
          name: test2
          version: 12.16.0
          requires: 
            - build
      - node/test:
          name: test3
          version: 10.19.0
          requires: 
            - build
      - deploy:
          name: netlifydeploy
          requires:
            - test1
            - test2
            - test3
          filters:
            branches:
              only: main
      - cypress/run:
          name: cypresstests
          record: true
          #  store_artifacts: true
          requires:
            - netlifydeploy