# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
#   cypress: cypress-io/cypress@1.26.0
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#            name: cypresstests
#            record: true
#            store_artifacts: true
#     - heroku/deploy-via-git:
#           requires:
#             - cypresstests
#           filters:
#             branches:
#               only: main

version: 2.1

orbs:
  node: circleci/node@3.0.0
  cypress: cypress-io/cypress@1.26.0
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    docker:
      - image: cimg/node:13.11.0

    steps: 
      - checkout
      # - run:
      #     name: Install libs
      #     command: sudo apt-get install libxtst6 libgconf-2-4 libnss3 libasound2 libgtk-3-0 libxss1
      - run: npm install
      # - run: cypress install
      # - run: npm run e2e
      # - run:
      #     name: Deploy
      #     command: '${hook}'
  deploy:
    steps:
      - run:
          command: curl -X POST -d {} ${hook}

workflows:
  matrix-tests:
    jobs:
      - build
      - node/test:
          name: test1
          version: 13.11.0
          requires: 
            - build
      - node/test:
          name: test2
          version: 12.16.0
          requires: 
            - build
      - node/test:
          name: test3
          version: 10.19.0
          requires: 
            - build
      # - heroku/deploy-via-git:
      #      name: herokudeploy
      #      requires:
      #       - test1
      #       - test2
      #       - test3
      #      filters:
      #       branches:
      #         only: main
      - deploy:
          name: netlifydeploy
          requires: 
            - test1
            - test2
            - test3
            filters:
              branches:
                only: main
      - cypress/run:
           name: cypresstests
           record: true
           store_artifacts: true
           requires:
            - netlifydeploy