version: 2.1

orbs:
  node: circleci/node@3.0.0
  # Add the cypress orb beneath this line
 

jobs:
  build:
    docker:
      - image: cimg/node:13.11.0
    steps: 
      - checkout
      - run: npm install
  deploy:
    docker:
      - image: cimg/node:13.11.0
    steps:
      - run:
          # add your environment variable between the ${}
          command: curl -X POST -d {} ${}

workflows:
  main:
    jobs:
      - build
      - node/test:
          name: test1
          version: 13.11.0
          requires: 
            - build
      - node/test:
          name: test2
          version: 12.16.0
          requires: 
            - build
      # add a node test for version 10.19.0 (don't forget to give it a name) and it should require build
      - deploy:
          name: netlifydeploy
          requires:
            - test1
            - test2
            - test3
          filters:
            branches:
              only: main
      # - cypress/run:
      #     name: cypresstests
      #     record: true
          #  store_artifacts: true
          # requires:
          #   - netlifydeploy
