version: 2.1
orbs:
  node: circleci/node@3.0.0
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
           name: cypresstests
           record: true
           store_artifacts: true
    - heroku/deploy-via-git:
          requires:
            - cypresstests
          filters:
            branches:
              only: main
